[tool.bumpversion]
current_version = "1.1.0"
serialize = ["({major}, {minor}, {patch})"]
commit = true
tag = false
message = "auto: bump version to {new_version}"

[[tool.bumpversion.files]]
filename = "src/_version.py"
search = "__version_info__ = {current_version}"
replace = "__version_info__ = {new_version}"
