[tool.bumpversion]
current_version = "1.1.0"
commit = true
tag = false
message = "auto: bump version to {new_version}"

[[tool.bumpversion.files]]
filename = "src/_version.py"
search = "__version_info__ = ({major}, {minor}, {patch})"
replace = "__version_info__ = ({new_major}, {new_minor}, {new_patch})"
