[tool.bumpversion]
current_version = "1.1.2"
serialize = ["{major}.{minor}.{patch}"]
commit = true
tag = false
message = "auto: bump version to {new_version}"

[[tool.bumpversion.files]]
filename = "src/_version.py"
serialize = ["({major}, {minor}, {patch})"]
search = "__version_info__ = {current_version}"
replace = "__version_info__ = {new_version}"

[[tool.bumpversion.files]]
filename = ".bumpversion.toml"
serialize = ["{major}.{minor}.{patch}"]
search = 'current_version = "{current_version}"'
replace = 'current_version = "{new_version}"'

[[tool.bumpversion.files]]
glob = "**/*.md"
serialize = ["{major}.{minor}.{patch}"]
search = "**Version**: {current_version}"
replace = "**Version**: {new_version}"
ignore_missing_version = true
