name: "Lint"

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v7"

        - name: "Set up uv"
          uses: astral-sh/setup-uv@v10.2.0
          with:
            python-version: "3.14"
            enable-cache: true

        - name: "Install requirements"
          run: uv sync --locked

        - name: "Lint"
          run: uv run ruff check .

        - name: "Format"
          run: uv run ruff format . --check

  pytest:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v7"

        - name: "Set up uv"
          uses: astral-sh/setup-uv@v10.2.0
          with:
            python-version: "3.14"
            enable-cache: true

        - name: "Install requirements"
          run: uv sync --locked

        - name: "Test"
          run: uv run pytest
